# THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT!
# See the Makefile for creation details.

BIT_SCORES = {
  "pdb_1bqn_a": {
    "pdb_4mtp_a": 21.6
  },
  "pdb_1c0t_b": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_1c0u_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_1c2p_a": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_1c2p_b": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_1csj_b": {
    "pdb_4mtp_a": 15.0
  },
  "pdb_1d0e_b": {
    "pdb_4mtp_a": 16.5
  },
  "pdb_1d1u_a": {
    "pdb_4mtp_a": 16.5
  },
  "pdb_1h6k_y": {
    "pdb_4mtp_a": 12.7
  },
  "pdb_1hhs_a": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_1hi1_c": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_1jjc_b": {
    "pdb_4mtp_a": 16.5
  },
  "pdb_1jle_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_1jle_b": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_1khv_b": {
    "pdb_4mtp_a": 17.7
  },
  "pdb_1khw_b": {
    "pdb_4mtp_a": 17.7
  },
  "pdb_1kln_a": {
    "pdb_4mtp_a": 19.6
  },
  "pdb_1mu2_a": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_1muk_a": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_1mwh_a": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_1n1h_a": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_1n35_a": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_1n5y_a": {
    "pdb_4mtp_a": 21.2
  },
  "pdb_1qai_a": {
    "pdb_4mtp_a": 16.5
  },
  "pdb_1qai_b": {
    "pdb_4mtp_a": 16.5
  },
  "pdb_1qaj_b": {
    "pdb_4mtp_a": 16.5
  },
  "pdb_1raj_a": {
    "pdb_4mtp_a": 18.5
  },
  "pdb_1rdr_a": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_1s49_a": {
    "pdb_4mtp_a": 42.0
  },
  "pdb_1s4f_a": {
    "pdb_4mtp_a": 42.0
  },
  "pdb_1s4f_b": {
    "pdb_4mtp_a": 42.0
  },
  "pdb_1s4f_d": {
    "pdb_4mtp_a": 42.0
  },
  "pdb_1s6p_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_1s6p_b": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_1sh0_b": {
    "pdb_4mtp_a": 15.4
  },
  "pdb_1sh2_a": {
    "pdb_4mtp_a": 15.4
  },
  "pdb_1sh3_b": {
    "pdb_4mtp_a": 15.4
  },
  "pdb_1tp7_c": {
    "pdb_4mtp_a": 16.2
  },
  "pdb_1tp7_d": {
    "pdb_4mtp_a": 16.2
  },
  "pdb_1tql_a": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_1tvr_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_1u09_a": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_1u8s_b": {
    "pdb_4mtp_a": 15.8
  },
  "pdb_1uon_a": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_1uvk_a": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_1uvl_e": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_1uvm_b": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_1uvm_c": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_1uvn_a": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_1uvn_c": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_1uvn_e": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_1uwb_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_1vk8_c": {
    "pdb_4mtp_a": 13.5
  },
  "pdb_1wac_b": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_1xmb_a": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_1yvz_a": {
    "pdb_4mtp_a": 32.7
  },
  "pdb_1yz6_a": {
    "pdb_4mtp_a": 16.5
  },
  "pdb_2b6a_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_2cjq_a": {
    "pdb_4mtp_a": 47.4
  },
  "pdb_2cvi_a": {
    "pdb_4mtp_a": 12.7
  },
  "pdb_2f4f_a": {
    "pdb_4mtp_a": 16.2
  },
  "pdb_2fyx_a": {
    "pdb_4mtp_a": 18.5
  },
  "pdb_2g1h_a": {
    "pdb_4mtp_a": 19.2
  },
  "pdb_2hcs_a": {
    "pdb_4mtp_a": 1045.0
  },
  "pdb_2hfz_a": {
    "pdb_4mtp_a": 1110.0
  },
  "pdb_2ijd_2": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_2ily_a": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_2j7u_a": {
    "pdb_4mtp_a": 899.0
  },
  "pdb_2j7w_a": {
    "pdb_4mtp_a": 899.0
  },
  "pdb_2j8s_a": {
    "pdb_4mtp_a": 19.6
  },
  "pdb_2jl9_a": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_2jl9_c": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_2jlf_a": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_2jlf_b": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_2jlf_c": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_2opq_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_2opr_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_2pgg_a": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_2pus_a": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_2qe2_b": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_2qj1_a": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_2r70_a": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_2r72_a": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_2r7o_a": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_2r7q_a": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_2r7r_a": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_2r7t_a": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_2r7u_a": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_2r7v_a": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_2r7w_a": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_2r7x_a": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_2r7x_b": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_2uut_a": {
    "pdb_4mtp_a": 22.7
  },
  "pdb_2uuw_a": {
    "pdb_4mtp_a": 22.7
  },
  "pdb_2wk4_a": {
    "pdb_4mtp_a": 22.7
  },
  "pdb_2wk4_b": {
    "pdb_4mtp_a": 22.7
  },
  "pdb_2wom_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_2xi2_a": {
    "pdb_4mtp_a": 18.1
  },
  "pdb_2xwh_a": {
    "pdb_4mtp_a": 35.4
  },
  "pdb_2yi8_a": {
    "pdb_4mtp_a": 19.6
  },
  "pdb_2yi8_d": {
    "pdb_4mtp_a": 19.6
  },
  "pdb_2yi8_e": {
    "pdb_4mtp_a": 19.6
  },
  "pdb_2yia_g": {
    "pdb_4mtp_a": 19.6
  },
  "pdb_2yib_d": {
    "pdb_4mtp_a": 19.6
  },
  "pdb_2ykn_a": {
    "pdb_4mtp_a": 21.2
  },
  "pdb_2yng_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_3agp_a": {
    "pdb_4mtp_a": 22.3
  },
  "pdb_3agq_a": {
    "pdb_4mtp_a": 22.3
  },
  "pdb_3avt_a": {
    "pdb_4mtp_a": 22.3
  },
  "pdb_3avv_a": {
    "pdb_4mtp_a": 22.3
  },
  "pdb_3avw_a": {
    "pdb_4mtp_a": 22.3
  },
  "pdb_3avx_a": {
    "pdb_4mtp_a": 22.3
  },
  "pdb_3avy_a": {
    "pdb_4mtp_a": 22.3
  },
  "pdb_3bgr_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_3bre_b": {
    "pdb_4mtp_a": 17.7
  },
  "pdb_3cso_b": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_3cvk_a": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_3d28_a": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_3du5_a": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_3gsz_b": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_3h5y_a": {
    "pdb_4mtp_a": 15.4
  },
  "pdb_3hmj_h": {
    "pdb_4mtp_a": 18.5
  },
  "pdb_3i5k_a": {
    "pdb_4mtp_a": 35.4
  },
  "pdb_3i5k_d": {
    "pdb_4mtp_a": 35.4
  },
  "pdb_3kle_a": {
    "pdb_4mtp_a": 21.6
  },
  "pdb_3kle_e": {
    "pdb_4mtp_a": 21.6
  },
  "pdb_3kle_f": {
    "pdb_4mtp_a": 21.2
  },
  "pdb_3klf_a": {
    "pdb_4mtp_a": 21.2
  },
  "pdb_3klf_e": {
    "pdb_4mtp_a": 21.2
  },
  "pdb_3klg_e": {
    "pdb_4mtp_a": 21.6
  },
  "pdb_3kms_a": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_3mf5_b": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_3mmp_f": {
    "pdb_4mtp_a": 21.9
  },
  "pdb_3n6m_a": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_3n6n_a": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_3nai_c": {
    "pdb_4mtp_a": 21.9
  },
  "pdb_3ol8_a": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_3phe_c": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_3qid_a": {
    "pdb_4mtp_a": 21.9
  },
  "pdb_3qid_b": {
    "pdb_4mtp_a": 21.9
  },
  "pdb_3sfu_a": {
    "pdb_4mtp_a": 21.9
  },
  "pdb_3sfu_b": {
    "pdb_4mtp_a": 21.9
  },
  "pdb_3ske_a": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_3t19_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_3tyv_a": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_3v4i_a": {
    "pdb_4mtp_a": 21.2
  },
  "pdb_3v4i_b": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_3v6d_c": {
    "pdb_4mtp_a": 21.2
  },
  "pdb_3v6d_d": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_3v81_a": {
    "pdb_4mtp_a": 21.2
  },
  "pdb_3v81_c": {
    "pdb_4mtp_a": 21.2
  },
  "pdb_3vnu_a": {
    "pdb_4mtp_a": 22.3
  },
  "pdb_3vws_a": {
    "pdb_4mtp_a": 898.0
  },
  "pdb_3zef_e": {
    "pdb_4mtp_a": 18.1
  },
  "pdb_4a8f_a": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_4aex_b": {
    "pdb_4mtp_a": 35.4
  },
  "pdb_4b02_b": {
    "pdb_4mtp_a": 20.0
  },
  "pdb_4b3o_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_4c11_b": {
    "pdb_4mtp_a": 894.0
  },
  "pdb_4e78_a": {
    "pdb_4mtp_a": 35.0
  },
  "pdb_4eo8_b": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_4f5x_w": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_4g1q_b": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_4gzk_a": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_4h4o_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_4hdg_a": {
    "pdb_4mtp_a": 1320.0
  },
  "pdb_4hdg_b": {
    "pdb_4mtp_a": 1320.0
  },
  "pdb_4hhj_a": {
    "pdb_4mtp_a": 898.0
  },
  "pdb_4hkq_a": {
    "pdb_4mtp_a": 17.7
  },
  "pdb_4i43_b": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_4i7f_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_4icl_b": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_4id5_b": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_4ig3_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_4j02_b": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_4j08_a": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_4jtz_a": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_4ju3_b": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_4k4u_a": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_4k4u_e": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_4k4x_a": {
    "pdb_4mtp_a": 17.7
  },
  "pdb_4k6m_a": {
    "pdb_4mtp_a": 1313.0
  },
  "pdb_4k6m_b": {
    "pdb_4mtp_a": 1313.0
  },
  "pdb_4kko_b": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_4lsn_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_4m94_a": {
    "pdb_4mtp_a": 16.5
  },
  "pdb_4m95_a": {
    "pdb_4mtp_a": 16.5
  },
  "pdb_4mfb_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_4mfb_b": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_4mia_a": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_4mka_b": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_4mtp_a": {
    "pdb_4mtp_a": 1320.0
  },
  "pdb_4mtp_b": {
    "pdb_4mtp_a": 1320.0
  },
  "pdb_4mtp_c": {
    "pdb_4mtp_a": 1320.0
  },
  "pdb_4mtp_d": {
    "pdb_4mtp_a": 1320.0
  },
  "pdb_4nlo_a": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_4nly_a": {
    "pdb_4mtp_a": 18.9
  },
  "pdb_4nyz_a": {
    "pdb_4mtp_a": 21.9
  },
  "pdb_4nz0_b": {
    "pdb_4mtp_a": 21.9
  },
  "pdb_4nz0_c": {
    "pdb_4mtp_a": 21.9
  },
  "pdb_4o4r_a": {
    "pdb_4mtp_a": 21.9
  },
  "pdb_4o4r_c": {
    "pdb_4mtp_a": 21.9
  },
  "pdb_4ol8_a": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_4ol8_e": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_4ol8_f": {
    "pdb_4mtp_a": 17.3
  },
  "pdb_4oow_a": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_4oow_b": {
    "pdb_4mtp_a": 16.9
  },
  "pdb_4pqu_a": {
    "pdb_4mtp_a": 21.2
  },
  "pdb_4pqu_b": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_4pqu_c": {
    "pdb_4mtp_a": 21.2
  },
  "pdb_4puo_a": {
    "pdb_4mtp_a": 21.2
  },
  "pdb_4pwu_a": {
    "pdb_4mtp_a": 12.7
  },
  "pdb_4pwu_b": {
    "pdb_4mtp_a": 12.7
  },
  "pdb_4pwu_c": {
    "pdb_4mtp_a": 12.7
  },
  "pdb_4q0b_a": {
    "pdb_4mtp_a": 21.2
  },
  "pdb_4we1_a": {
    "pdb_4mtp_a": 20.8
  },
  "pdb_4wfy_a": {
    "pdb_4mtp_a": 17.7
  }
}
