# THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT!
# See the Makefile for creation details.

BIT_SCORES = {
  "1A1N-A": {
    "2HLA-A": 477.0
  },
  "1A6Z-C": {
    "2HLA-A": 181.0
  },
  "1EFX-A": {
    "2HLA-A": 476.0
  },
  "1JE6-A": {
    "2HLA-A": 130.0
  },
  "1JGD-A": {
    "2HLA-A": 478.0
  },
  "1JUF-A": {
    "2HLA-A": 399.0
  },
  "1K5N-A": {
    "2HLA-A": 478.0
  },
  "1KJ2-H": {
    "2HLA-A": 411.0
  },
  "1KJ2-I": {
    "2HLA-A": 411.0
  },
  "1M05-C": {
    "2HLA-A": 478.0
  },
  "1MHC-A": {
    "2HLA-A": 363.0
  },
  "1MVF-A": {
    "2HLA-A": 13.9
  },
  "1MWA-I": {
    "2HLA-A": 409.0
  },
  "1N3N-A": {
    "2HLA-A": 399.0
  },
  "1NAN-H": {
    "2HLA-A": 411.0
  },
  "1NEZ-A": {
    "2HLA-A": 362.0
  },
  "1T0N-A": {
    "2HLA-A": 414.0
  },
  "1T1Y-A": {
    "2HLA-A": 532.0
  },
  "1ZT1-A": {
    "2HLA-A": 393.0
  },
  "1ZVS-A": {
    "2HLA-A": 479.0
  },
  "1ZVS-D": {
    "2HLA-A": 479.0
  },
  "2AK4-K": {
    "2HLA-A": 478.0
  },
  "2BCK-A": {
    "2HLA-A": 501.0
  },
  "2CLV-A": {
    "2HLA-A": 414.0
  },
  "2FBJ-H": {
    "2HLA-A": 27.3
  },
  "2FWO-A": {
    "2HLA-A": 405.0
  },
  "2HLA-A": {
    "2HLA-A": 565.0
  },
  "2J88-L": {
    "2HLA-A": 31.6
  },
  "2PO6-G": {
    "2HLA-A": 13.5
  },
  "2QRI-A": {
    "2HLA-A": 413.0
  },
  "2QRS-A": {
    "2HLA-A": 410.0
  },
  "2QRS-B": {
    "2HLA-A": 410.0
  },
  "2R69-L": {
    "2HLA-A": 29.3
  },
  "2V2W-D": {
    "2HLA-A": 531.0
  },
  "2VE6-A": {
    "2HLA-A": 399.0
  },
  "2VLR-A": {
    "2HLA-A": 531.0
  },
  "2VLR-F": {
    "2HLA-A": 531.0
  },
  "2WBJ-D": {
    "2HLA-A": 28.9
  },
  "2WNG-A": {
    "2HLA-A": 38.1
  },
  "2WQR-B": {
    "2HLA-A": 29.3
  },
  "2XFX-A": {
    "2HLA-A": 415.0
  },
  "2Y7Q-D": {
    "2HLA-A": 29.3
  },
  "2YD5-A": {
    "2HLA-A": 13.9
  },
  "2YEZ-A": {
    "2HLA-A": 207.0
  },
  "3B9K-C": {
    "2HLA-A": 38.9
  },
  "3B9K-D": {
    "2HLA-A": 26.9
  },
  "3BUY-A": {
    "2HLA-A": 397.0
  },
  "3BZE-G": {
    "2HLA-A": 431.0
  },
  "3BZF-A": {
    "2HLA-A": 432.0
  },
  "3CDG-C": {
    "2HLA-A": 431.0
  },
  "3CFC-L": {
    "2HLA-A": 31.2
  },
  "3CH1-D": {
    "2HLA-A": 399.0
  },
  "3CH1-J": {
    "2HLA-A": 399.0
  },
  "3D2U-A": {
    "2HLA-A": 76.6
  },
  "3DBX-A": {
    "2HLA-A": 45.1
  },
  "3DXA-F": {
    "2HLA-A": 459.0
  },
  "3E6F-A": {
    "2HLA-A": 399.0
  },
  "3E6H-A": {
    "2HLA-A": 396.0
  },
  "3EOT-L": {
    "2HLA-A": 31.2
  },
  "3FFC-E": {
    "2HLA-A": 28.9
  },
  "3FFC-F": {
    "2HLA-A": 478.0
  },
  "3FOL-A": {
    "2HLA-A": 401.0
  },
  "3FON-A": {
    "2HLA-A": 401.0
  },
  "3FQW-A": {
    "2HLA-A": 532.0
  },
  "3FQX-A": {
    "2HLA-A": 532.0
  },
  "3FTG-A": {
    "2HLA-A": 399.0
  },
  "3G6D-L": {
    "2HLA-A": 33.5
  },
  "3GI8-L": {
    "2HLA-A": 31.2
  },
  "3GJF-A": {
    "2HLA-A": 531.0
  },
  "3GSV-A": {
    "2HLA-A": 534.0
  },
  "3GSW-A": {
    "2HLA-A": 534.0
  },
  "3H9S-A": {
    "2HLA-A": 532.0
  },
  "3HE6-C": {
    "2HLA-A": 13.9
  },
  "3HLA-A": {
    "2HLA-A": 533.0
  },
  "3HNS-L": {
    "2HLA-A": 32.0
  },
  "3I2C-L": {
    "2HLA-A": 30.8
  },
  "3I6G-A": {
    "2HLA-A": 532.0
  },
  "3KPP-A": {
    "2HLA-A": 459.0
  },
  "3LKR-A": {
    "2HLA-A": 479.0
  },
  "3LQZ-A": {
    "2HLA-A": 42.0
  },
  "3MGO-A": {
    "2HLA-A": 532.0
  },
  "3MYJ-D": {
    "2HLA-A": 532.0
  },
  "3NWM-A": {
    "2HLA-A": 405.0
  },
  "3O6F-F": {
    "2HLA-A": 50.1
  },
  "3P4O-D": {
    "2HLA-A": 411.0
  },
  "3P73-A": {
    "2HLA-A": 195.0
  },
  "3P77-A": {
    "2HLA-A": 195.0
  },
  "3P9L-A": {
    "2HLA-A": 411.0
  },
  "3PAB-A": {
    "2HLA-A": 411.0
  },
  "3PL6-B": {
    "2HLA-A": 58.2
  },
  "3PL6-D": {
    "2HLA-A": 28.9
  },
  "3PQY-P": {
    "2HLA-A": 397.0
  },
  "3PWU-A": {
    "2HLA-A": 422.0
  },
  "3Q5Y-A": {
    "2HLA-A": 28.5
  },
  "3QDM-D": {
    "2HLA-A": 0.0
  },
  "3QQ3-A": {
    "2HLA-A": 417.0
  },
  "3QS9-E": {
    "2HLA-A": 15.8
  },
  "3R0N-A": {
    "2HLA-A": 12.7
  },
  "3RA7-M": {
    "2HLA-A": 31.6
  },
  "3RHW-N": {
    "2HLA-A": 38.1
  },
  "3RWC-A": {
    "2HLA-A": 460.0
  },
  "3S6C-A": {
    "2HLA-A": 51.2
  },
  "3S97-C": {
    "2HLA-A": 17.7
  },
  "3SJV-K": {
    "2HLA-A": 478.0
  },
  "3SPV-A": {
    "2HLA-A": 478.0
  },
  "3TBT-D": {
    "2HLA-A": 401.0
  },
  "3TBW-A": {
    "2HLA-A": 401.0
  },
  "3TBY-J": {
    "2HLA-A": 401.0
  },
  "3TJH-A": {
    "2HLA-A": 258.0
  },
  "3VJ6-A": {
    "2HLA-A": 401.0
  },
  "3VXN-A": {
    "2HLA-A": 501.0
  },
  "4E0R-D": {
    "2HLA-A": 218.0
  },
  "4EI6-B": {
    "2HLA-A": 28.9
  },
  "4EN3-A": {
    "2HLA-A": 0.0
  },
  "4G42-A": {
    "2HLA-A": 218.0
  },
  "4HKJ-M": {
    "2HLA-A": 411.0
  },
  "4HUU-A": {
    "2HLA-A": 399.0
  },
  "4HUW-E": {
    "2HLA-A": 399.0
  },
  "4IHO-A": {
    "2HLA-A": 398.0
  },
  "4IIQ-C": {
    "2HLA-A": 213.0
  },
  "4JFD-E": {
    "2HLA-A": 28.5
  },
  "4JFQ-A": {
    "2HLA-A": 531.0
  },
  "4JR9-L": {
    "2HLA-A": 31.2
  },
  "4K71-B": {
    "2HLA-A": 105.0
  },
  "4L8S-C": {
    "2HLA-A": 213.0
  },
  "4L9L-C": {
    "2HLA-A": 213.0
  },
  "4LCW-C": {
    "2HLA-A": 209.0
  },
  "4LCY-A": {
    "2HLA-A": 487.0
  },
  "4LHJ-B": {
    "2HLA-A": 13.9
  },
  "4LP5-A": {
    "2HLA-A": 20.0
  },
  "4NQC-A": {
    "2HLA-A": 208.0
  },
  "4NQE-A": {
    "2HLA-A": 208.0
  },
  "4NQX-C": {
    "2HLA-A": 513.0
  },
  "4P49-A": {
    "2HLA-A": 13.9
  },
  "4PJ7-C": {
    "2HLA-A": 208.0
  },
  "4PJB-C": {
    "2HLA-A": 208.0
  },
  "4PJE-C": {
    "2HLA-A": 208.0
  },
  "4PJF-C": {
    "2HLA-A": 208.0
  },
  "4PJH-C": {
    "2HLA-A": 208.0
  },
  "4PRH-A": {
    "2HLA-A": 467.0
  },
  "4TVS-A": {
    "2HLA-A": 16.5
  }
}
