# THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT!
# See the Makefile for creation details.

BIT_SCORES = {
  "pdb_1a43_a": {
    "pdb_4ph0_a": 32.0
  },
  "pdb_1a8o_a": {
    "pdb_4ph0_a": 31.2
  },
  "pdb_1ak4_c": {
    "pdb_4ph0_a": 13.1
  },
  "pdb_1aum_a": {
    "pdb_4ph0_a": 32.3
  },
  "pdb_1baj_a": {
    "pdb_4ph0_a": 32.0
  },
  "pdb_1d1d_a": {
    "pdb_4ph0_a": 38.1
  },
  "pdb_1e5r_a": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_1eia_a": {
    "pdb_4ph0_a": 35.8
  },
  "pdb_1em9_a": {
    "pdb_4ph0_a": 16.2
  },
  "pdb_1eoq_a": {
    "pdb_4ph0_a": 31.2
  },
  "pdb_1fkm_a": {
    "pdb_4ph0_a": 17.7
  },
  "pdb_1g03_a": {
    "pdb_4ph0_a": 82.8
  },
  "pdb_1gux_a": {
    "pdb_4ph0_a": 12.3
  },
  "pdb_1gwp_a": {
    "pdb_4ph0_a": 13.1
  },
  "pdb_1h3l_b": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_1iqp_d": {
    "pdb_4ph0_a": 13.5
  },
  "pdb_1j8m_f": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_1jfj_a": {
    "pdb_4ph0_a": 11.5
  },
  "pdb_1jgt_b": {
    "pdb_4ph0_a": 14.6
  },
  "pdb_1l2f_a": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_1l6n_a": {
    "pdb_4ph0_a": 18.1
  },
  "pdb_1or7_a": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_1p7n_a": {
    "pdb_4ph0_a": 16.2
  },
  "pdb_1qzw_c": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_1qzx_b": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_1ry1_u": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_1sg7_a": {
    "pdb_4ph0_a": 16.9
  },
  "pdb_1sxj_e": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_1u7k_c": {
    "pdb_4ph0_a": 15.0
  },
  "pdb_1vhn_a": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_1wgw_a": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_1zu5_b": {
    "pdb_4ph0_a": 14.6
  },
  "pdb_2eia_b": {
    "pdb_4ph0_a": 35.8
  },
  "pdb_2fi2_a": {
    "pdb_4ph0_a": 15.0
  },
  "pdb_2gol_b": {
    "pdb_4ph0_a": 13.1
  },
  "pdb_2gon_c": {
    "pdb_4ph0_a": 13.1
  },
  "pdb_2hg4_d": {
    "pdb_4ph0_a": 15.0
  },
  "pdb_2hiv_a": {
    "pdb_4ph0_a": 19.6
  },
  "pdb_2i8b_b": {
    "pdb_4ph0_a": 12.7
  },
  "pdb_2j28_9": {
    "pdb_4ph0_a": 17.7
  },
  "pdb_2j37_w": {
    "pdb_4ph0_a": 18.1
  },
  "pdb_2kgf_a": {
    "pdb_4ph0_a": 16.9
  },
  "pdb_2kod_a": {
    "pdb_4ph0_a": 33.5
  },
  "pdb_2lqu_a": {
    "pdb_4ph0_a": 13.9
  },
  "pdb_2m8l_b": {
    "pdb_4ph0_a": 32.7
  },
  "pdb_2m8n_a": {
    "pdb_4ph0_a": 32.7
  },
  "pdb_2pwm_f": {
    "pdb_4ph0_a": 13.1
  },
  "pdb_2pwo_b": {
    "pdb_4ph0_a": 13.1
  },
  "pdb_2pxr_c": {
    "pdb_4ph0_a": 13.1
  },
  "pdb_2qw6_d": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_2r9g_k": {
    "pdb_4ph0_a": 15.8
  },
  "pdb_2v4x_a": {
    "pdb_4ph0_a": 27.7
  },
  "pdb_2wlv_a": {
    "pdb_4ph0_a": 13.1
  },
  "pdb_2x82_a": {
    "pdb_4ph0_a": 13.5
  },
  "pdb_2x83_c": {
    "pdb_4ph0_a": 13.1
  },
  "pdb_2xgu_b": {
    "pdb_4ph0_a": 20.4
  },
  "pdb_2xgv_a": {
    "pdb_4ph0_a": 13.1
  },
  "pdb_2xkv_a": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_2ygu_b": {
    "pdb_4ph0_a": 14.6
  },
  "pdb_3b4q_b": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_3bge_b": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_3bp9_m": {
    "pdb_4ph0_a": 15.4
  },
  "pdb_3ckd_b": {
    "pdb_4ph0_a": 17.3
  },
  "pdb_3ctd_b": {
    "pdb_4ph0_a": 16.5
  },
  "pdb_3dm5_b": {
    "pdb_4ph0_a": 14.2
  },
  "pdb_3dmd_b": {
    "pdb_4ph0_a": 13.5
  },
  "pdb_3g1g_b": {
    "pdb_4ph0_a": 37.7
  },
  "pdb_3g1i_a": {
    "pdb_4ph0_a": 37.7
  },
  "pdb_3g21_a": {
    "pdb_4ph0_a": 37.7
  },
  "pdb_3glf_d": {
    "pdb_4ph0_a": 16.5
  },
  "pdb_3glh_i": {
    "pdb_4ph0_a": 16.5
  },
  "pdb_3gli_h": {
    "pdb_4ph0_a": 16.5
  },
  "pdb_3gv2_d": {
    "pdb_4ph0_a": 32.0
  },
  "pdb_3h47_a": {
    "pdb_4ph0_a": 32.7
  },
  "pdb_3h4e_c": {
    "pdb_4ph0_a": 32.7
  },
  "pdb_3hc1_a": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_3hmj_b": {
    "pdb_4ph0_a": 16.2
  },
  "pdb_3ibj_a": {
    "pdb_4ph0_a": 16.5
  },
  "pdb_3j34_v": {
    "pdb_4ph0_a": 34.3
  },
  "pdb_3j7y_h": {
    "pdb_4ph0_a": 15.4
  },
  "pdb_3kl4_a": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_3lhr_b": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_3lry_a": {
    "pdb_4ph0_a": 32.0
  },
  "pdb_3m1t_a": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_3mge_a": {
    "pdb_4ph0_a": 32.7
  },
  "pdb_3ndb_b": {
    "pdb_4ph0_a": 16.9
  },
  "pdb_3nte_b": {
    "pdb_4ph0_a": 34.3
  },
  "pdb_3p05_d": {
    "pdb_4ph0_a": 32.7
  },
  "pdb_3pvs_c": {
    "pdb_4ph0_a": 15.0
  },
  "pdb_3u5z_d": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_3u60_b": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_3u61_d": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_3v7o_a": {
    "pdb_4ph0_a": 19.2
  },
  "pdb_4ams_a": {
    "pdb_4ph0_a": 15.8
  },
  "pdb_4b4n_a": {
    "pdb_4ph0_a": 13.1
  },
  "pdb_4bhx_b": {
    "pdb_4ph0_a": 11.9
  },
  "pdb_4c7o_a": {
    "pdb_4ph0_a": 17.7
  },
  "pdb_4e6s_a": {
    "pdb_4ph0_a": 13.5
  },
  "pdb_4htw_a": {
    "pdb_4ph0_a": 11.9
  },
  "pdb_4hzu_t": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_4pgr_a": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_4ph0_a": {
    "pdb_4ph0_a": 436.0
  },
  "pdb_4ph0_b": {
    "pdb_4ph0_a": 436.0
  },
  "pdb_4ph1_c": {
    "pdb_4ph0_a": 179.0
  },
  "pdb_4ph2_a": {
    "pdb_4ph0_a": 260.0
  },
  "pdb_4tkq_a": {
    "pdb_4ph0_a": 0.0
  },
  "pdb_4ue5_d": {
    "pdb_4ph0_a": 18.1
  },
  "pdb_4usn_h": {
    "pdb_4ph0_a": 33.1
  },
  "pdb_4wym_b": {
    "pdb_4ph0_a": 32.7
  },
  "pdb_4x3x_a": {
    "pdb_4ph0_a": 17.3
  },
  "pdb_4xfy_a": {
    "pdb_4ph0_a": 32.7
  },
  "pdb_4zvd_b": {
    "pdb_4ph0_a": 15.4
  },
  "pdb_5a9e_n": {
    "pdb_4ph0_a": 38.5
  },
  "pdb_5dvw_c": {
    "pdb_4ph0_a": 12.7
  }
}
