# THIS FILE IS AUTOMATICALLY GENERATED - DO NOT EDIT!
# See the Makefile for creation details.

BIT_SCORES = {
  "1BQN-A": {
    "4MTP-A": 21.6
  },
  "1C0T-B": {
    "4MTP-A": 20.8
  },
  "1C0U-A": {
    "4MTP-A": 20.8
  },
  "1C2P-A": {
    "4MTP-A": 16.9
  },
  "1C2P-B": {
    "4MTP-A": 16.9
  },
  "1CSJ-B": {
    "4MTP-A": 15.0
  },
  "1D0E-B": {
    "4MTP-A": 16.5
  },
  "1D1U-A": {
    "4MTP-A": 16.5
  },
  "1H6K-Y": {
    "4MTP-A": 12.7
  },
  "1HHS-A": {
    "4MTP-A": 20.0
  },
  "1HI1-C": {
    "4MTP-A": 20.0
  },
  "1JJC-B": {
    "4MTP-A": 16.5
  },
  "1JLE-A": {
    "4MTP-A": 20.8
  },
  "1JLE-B": {
    "4MTP-A": 20.8
  },
  "1KHV-B": {
    "4MTP-A": 17.7
  },
  "1KHW-B": {
    "4MTP-A": 17.7
  },
  "1KLN-A": {
    "4MTP-A": 19.6
  },
  "1MU2-A": {
    "4MTP-A": 17.3
  },
  "1MUK-A": {
    "4MTP-A": 18.9
  },
  "1MWH-A": {
    "4MTP-A": 18.9
  },
  "1N1H-A": {
    "4MTP-A": 18.9
  },
  "1N35-A": {
    "4MTP-A": 18.9
  },
  "1N5Y-A": {
    "4MTP-A": 21.2
  },
  "1QAI-A": {
    "4MTP-A": 16.5
  },
  "1QAI-B": {
    "4MTP-A": 16.5
  },
  "1QAJ-B": {
    "4MTP-A": 16.5
  },
  "1RAJ-A": {
    "4MTP-A": 18.5
  },
  "1RDR-A": {
    "4MTP-A": 18.9
  },
  "1S49-A": {
    "4MTP-A": 42.0
  },
  "1S4F-A": {
    "4MTP-A": 42.0
  },
  "1S4F-B": {
    "4MTP-A": 42.0
  },
  "1S4F-D": {
    "4MTP-A": 42.0
  },
  "1S6P-A": {
    "4MTP-A": 20.8
  },
  "1S6P-B": {
    "4MTP-A": 20.8
  },
  "1SH0-B": {
    "4MTP-A": 15.4
  },
  "1SH2-A": {
    "4MTP-A": 15.4
  },
  "1SH3-B": {
    "4MTP-A": 15.4
  },
  "1TP7-C": {
    "4MTP-A": 16.2
  },
  "1TP7-D": {
    "4MTP-A": 16.2
  },
  "1TQL-A": {
    "4MTP-A": 18.9
  },
  "1TVR-A": {
    "4MTP-A": 20.8
  },
  "1U09-A": {
    "4MTP-A": 17.3
  },
  "1U8S-B": {
    "4MTP-A": 15.8
  },
  "1UON-A": {
    "4MTP-A": 18.9
  },
  "1UVK-A": {
    "4MTP-A": 20.0
  },
  "1UVL-E": {
    "4MTP-A": 20.0
  },
  "1UVM-B": {
    "4MTP-A": 20.0
  },
  "1UVM-C": {
    "4MTP-A": 20.0
  },
  "1UVN-A": {
    "4MTP-A": 20.0
  },
  "1UVN-C": {
    "4MTP-A": 20.0
  },
  "1UVN-E": {
    "4MTP-A": 20.0
  },
  "1UWB-A": {
    "4MTP-A": 20.8
  },
  "1VK8-C": {
    "4MTP-A": 13.5
  },
  "1WAC-B": {
    "4MTP-A": 20.0
  },
  "1XMB-A": {
    "4MTP-A": 20.0
  },
  "1YVZ-A": {
    "4MTP-A": 32.7
  },
  "1YZ6-A": {
    "4MTP-A": 16.5
  },
  "2B6A-A": {
    "4MTP-A": 20.8
  },
  "2CJQ-A": {
    "4MTP-A": 47.4
  },
  "2CVI-A": {
    "4MTP-A": 12.7
  },
  "2F4F-A": {
    "4MTP-A": 16.2
  },
  "2FYX-A": {
    "4MTP-A": 18.5
  },
  "2G1H-A": {
    "4MTP-A": 19.2
  },
  "2HCS-A": {
    "4MTP-A": 1045.0
  },
  "2HFZ-A": {
    "4MTP-A": 1110.0
  },
  "2IJD-2": {
    "4MTP-A": 18.9
  },
  "2ILY-A": {
    "4MTP-A": 18.9
  },
  "2J7U-A": {
    "4MTP-A": 899.0
  },
  "2J7W-A": {
    "4MTP-A": 899.0
  },
  "2J8S-A": {
    "4MTP-A": 19.6
  },
  "2JL9-A": {
    "4MTP-A": 20.0
  },
  "2JL9-C": {
    "4MTP-A": 20.0
  },
  "2JLF-A": {
    "4MTP-A": 20.0
  },
  "2JLF-B": {
    "4MTP-A": 20.0
  },
  "2JLF-C": {
    "4MTP-A": 20.0
  },
  "2OPQ-A": {
    "4MTP-A": 20.8
  },
  "2OPR-A": {
    "4MTP-A": 20.8
  },
  "2PGG-A": {
    "4MTP-A": 20.0
  },
  "2PUS-A": {
    "4MTP-A": 20.0
  },
  "2QE2-B": {
    "4MTP-A": 16.9
  },
  "2QJ1-A": {
    "4MTP-A": 20.0
  },
  "2R70-A": {
    "4MTP-A": 20.0
  },
  "2R72-A": {
    "4MTP-A": 20.0
  },
  "2R7O-A": {
    "4MTP-A": 17.3
  },
  "2R7Q-A": {
    "4MTP-A": 17.3
  },
  "2R7R-A": {
    "4MTP-A": 17.3
  },
  "2R7T-A": {
    "4MTP-A": 17.3
  },
  "2R7U-A": {
    "4MTP-A": 17.3
  },
  "2R7V-A": {
    "4MTP-A": 17.3
  },
  "2R7W-A": {
    "4MTP-A": 17.3
  },
  "2R7X-A": {
    "4MTP-A": 17.3
  },
  "2R7X-B": {
    "4MTP-A": 17.3
  },
  "2UUT-A": {
    "4MTP-A": 22.7
  },
  "2UUW-A": {
    "4MTP-A": 22.7
  },
  "2WK4-A": {
    "4MTP-A": 22.7
  },
  "2WK4-B": {
    "4MTP-A": 22.7
  },
  "2WOM-A": {
    "4MTP-A": 20.8
  },
  "2XI2-A": {
    "4MTP-A": 18.1
  },
  "2XWH-A": {
    "4MTP-A": 35.4
  },
  "2YI8-A": {
    "4MTP-A": 19.6
  },
  "2YI8-D": {
    "4MTP-A": 19.6
  },
  "2YI8-E": {
    "4MTP-A": 19.6
  },
  "2YIA-G": {
    "4MTP-A": 19.6
  },
  "2YIB-D": {
    "4MTP-A": 19.6
  },
  "2YKN-A": {
    "4MTP-A": 21.2
  },
  "2YNG-A": {
    "4MTP-A": 20.8
  },
  "3AGP-A": {
    "4MTP-A": 22.3
  },
  "3AGQ-A": {
    "4MTP-A": 22.3
  },
  "3AVT-A": {
    "4MTP-A": 22.3
  },
  "3AVV-A": {
    "4MTP-A": 22.3
  },
  "3AVW-A": {
    "4MTP-A": 22.3
  },
  "3AVX-A": {
    "4MTP-A": 22.3
  },
  "3AVY-A": {
    "4MTP-A": 22.3
  },
  "3BGR-A": {
    "4MTP-A": 20.8
  },
  "3BRE-B": {
    "4MTP-A": 17.7
  },
  "3CSO-B": {
    "4MTP-A": 16.9
  },
  "3CVK-A": {
    "4MTP-A": 16.9
  },
  "3D28-A": {
    "4MTP-A": 16.9
  },
  "3DU5-A": {
    "4MTP-A": 20.0
  },
  "3GSZ-B": {
    "4MTP-A": 17.3
  },
  "3H5Y-A": {
    "4MTP-A": 15.4
  },
  "3HMJ-H": {
    "4MTP-A": 18.5
  },
  "3I5K-A": {
    "4MTP-A": 35.4
  },
  "3I5K-D": {
    "4MTP-A": 35.4
  },
  "3KLE-A": {
    "4MTP-A": 21.6
  },
  "3KLE-E": {
    "4MTP-A": 21.6
  },
  "3KLE-F": {
    "4MTP-A": 21.2
  },
  "3KLF-A": {
    "4MTP-A": 21.2
  },
  "3KLF-E": {
    "4MTP-A": 21.2
  },
  "3KLG-E": {
    "4MTP-A": 21.6
  },
  "3KMS-A": {
    "4MTP-A": 17.3
  },
  "3MF5-B": {
    "4MTP-A": 16.9
  },
  "3MMP-F": {
    "4MTP-A": 21.9
  },
  "3N6M-A": {
    "4MTP-A": 18.9
  },
  "3N6N-A": {
    "4MTP-A": 18.9
  },
  "3NAI-C": {
    "4MTP-A": 21.9
  },
  "3OL8-A": {
    "4MTP-A": 18.9
  },
  "3PHE-C": {
    "4MTP-A": 16.9
  },
  "3QID-A": {
    "4MTP-A": 21.9
  },
  "3QID-B": {
    "4MTP-A": 21.9
  },
  "3SFU-A": {
    "4MTP-A": 21.9
  },
  "3SFU-B": {
    "4MTP-A": 21.9
  },
  "3SKE-A": {
    "4MTP-A": 16.9
  },
  "3T19-A": {
    "4MTP-A": 20.8
  },
  "3TYV-A": {
    "4MTP-A": 16.9
  },
  "3V4I-A": {
    "4MTP-A": 21.2
  },
  "3V4I-B": {
    "4MTP-A": 20.8
  },
  "3V6D-C": {
    "4MTP-A": 21.2
  },
  "3V6D-D": {
    "4MTP-A": 20.8
  },
  "3V81-A": {
    "4MTP-A": 21.2
  },
  "3V81-C": {
    "4MTP-A": 21.2
  },
  "3VNU-A": {
    "4MTP-A": 22.3
  },
  "3VWS-A": {
    "4MTP-A": 898.0
  },
  "3ZEF-E": {
    "4MTP-A": 18.1
  },
  "4A8F-A": {
    "4MTP-A": 20.0
  },
  "4AEX-B": {
    "4MTP-A": 35.4
  },
  "4B02-B": {
    "4MTP-A": 20.0
  },
  "4B3O-A": {
    "4MTP-A": 20.8
  },
  "4C11-B": {
    "4MTP-A": 894.0
  },
  "4E78-A": {
    "4MTP-A": 35.0
  },
  "4EO8-B": {
    "4MTP-A": 16.9
  },
  "4F5X-W": {
    "4MTP-A": 17.3
  },
  "4G1Q-B": {
    "4MTP-A": 20.8
  },
  "4GZK-A": {
    "4MTP-A": 16.9
  },
  "4H4O-A": {
    "4MTP-A": 20.8
  },
  "4HDG-A": {
    "4MTP-A": 1320.0
  },
  "4HDG-B": {
    "4MTP-A": 1320.0
  },
  "4HHJ-A": {
    "4MTP-A": 898.0
  },
  "4HKQ-A": {
    "4MTP-A": 17.7
  },
  "4I43-B": {
    "4MTP-A": 18.9
  },
  "4I7F-A": {
    "4MTP-A": 20.8
  },
  "4ICL-B": {
    "4MTP-A": 20.8
  },
  "4ID5-B": {
    "4MTP-A": 20.8
  },
  "4IG3-A": {
    "4MTP-A": 20.8
  },
  "4J02-B": {
    "4MTP-A": 16.9
  },
  "4J08-A": {
    "4MTP-A": 16.9
  },
  "4JTZ-A": {
    "4MTP-A": 16.9
  },
  "4JU3-B": {
    "4MTP-A": 16.9
  },
  "4K4U-A": {
    "4MTP-A": 18.9
  },
  "4K4U-E": {
    "4MTP-A": 18.9
  },
  "4K4X-A": {
    "4MTP-A": 17.7
  },
  "4K6M-A": {
    "4MTP-A": 1313.0
  },
  "4K6M-B": {
    "4MTP-A": 1313.0
  },
  "4KKO-B": {
    "4MTP-A": 20.8
  },
  "4LSN-A": {
    "4MTP-A": 20.8
  },
  "4M94-A": {
    "4MTP-A": 16.5
  },
  "4M95-A": {
    "4MTP-A": 16.5
  },
  "4MFB-A": {
    "4MTP-A": 20.8
  },
  "4MFB-B": {
    "4MTP-A": 20.8
  },
  "4MIA-A": {
    "4MTP-A": 16.9
  },
  "4MKA-B": {
    "4MTP-A": 16.9
  },
  "4MTP-A": {
    "4MTP-A": 1320.0
  },
  "4MTP-B": {
    "4MTP-A": 1320.0
  },
  "4MTP-C": {
    "4MTP-A": 1320.0
  },
  "4MTP-D": {
    "4MTP-A": 1320.0
  },
  "4NLO-A": {
    "4MTP-A": 18.9
  },
  "4NLY-A": {
    "4MTP-A": 18.9
  },
  "4NYZ-A": {
    "4MTP-A": 21.9
  },
  "4NZ0-B": {
    "4MTP-A": 21.9
  },
  "4NZ0-C": {
    "4MTP-A": 21.9
  },
  "4O4R-A": {
    "4MTP-A": 21.9
  },
  "4O4R-C": {
    "4MTP-A": 21.9
  },
  "4OL8-A": {
    "4MTP-A": 17.3
  },
  "4OL8-E": {
    "4MTP-A": 17.3
  },
  "4OL8-F": {
    "4MTP-A": 17.3
  },
  "4OOW-A": {
    "4MTP-A": 16.9
  },
  "4OOW-B": {
    "4MTP-A": 16.9
  },
  "4PQU-A": {
    "4MTP-A": 21.2
  },
  "4PQU-B": {
    "4MTP-A": 20.8
  },
  "4PQU-C": {
    "4MTP-A": 21.2
  },
  "4PUO-A": {
    "4MTP-A": 21.2
  },
  "4PWU-A": {
    "4MTP-A": 12.7
  },
  "4PWU-B": {
    "4MTP-A": 12.7
  },
  "4PWU-C": {
    "4MTP-A": 12.7
  },
  "4Q0B-A": {
    "4MTP-A": 21.2
  },
  "4WE1-A": {
    "4MTP-A": 20.8
  },
  "4WFY-A": {
    "4MTP-A": 17.7
  }
}
